### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by montaz708**
Hey! Wanted to test this package out but our scan tool needs to see a license key in your package.json file, would it be alright if I added this?

### CODE REVIEW

**Review by joel-wenzel — APPROVED** [review]

**Review by joel-wenzel — CHANGES_REQUESTED** [review]
`projects/ng-flowchart/package.json` is the file you want to update actually. The root package json is just for the playground. 

Currently I am not auto incrementing package version in the action so you will want to set verision to `"version": "1.0.0-beta.12",`

**Comment by montaz708** [comment]
Hey Joel! Appreciate you reaching back out! I'm pretty sure our scan tool is looking in the root. The scan tool is downloading whatever comes from the `npm i @joel-wenzel/ng-flowchart@1.0.0-beta.11` . Sorry, I'm a JS noob, so I don't know how the installs work when we're downloading packages from the "public" space.

**Comment by montaz708** [comment]
Hang on, I understand what you're saying now, let me make that change.

**Comment by montaz708** [comment]
how's that @joel-wenzel ?

**Review by joel-wenzel — APPROVED** [review]
Looks good now

**Comment by montaz708** [comment]
Thanks again Joel!

**Pull request merged**
